In [1]:
import tensorflow as tf
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

# First FT model
### Identifying the species of Iris flower
## Classic ML problem

In [2]:

# Set random seed for reproducibility
np.random.seed(0)
iris = datasets.load_iris()
data = iris.data
labels = iris.target

In [7]:
num_elements = len(labels)
print(data[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
# Use shuffled indexing to shuffle dataset

shuffled_indices = np.random.permutation(num_elements)